name: flutter_explorer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^3.1.1
  dio: ^3.0.10
  retrofit: ^1.3.4+1
  pretty_dio_logger: ^1.1.1
  freezed_annotation: ^0.12.0

dev_dependencies:
  build_runner: ^1.10.3
  json_serializable: ^3.5.1
  retrofit_generator: ^1.4.1+3
  freezed: ^0.12.2

flutter:
  uses-material-design: true

